host: 10.10.10.197
port: 443

url: "https://randacek.dev"
baseurl: ""

include: ['.htaccess']

exclude: [
    "README.md",
    "run",
    "runlocal",
    "fullchain.pem",
    "privkey.pem",
    "content/stuff.md"
]
